version: "3.1"

services:
  web:
    image: registry:5000/web
    build: web
    ports:
      - 80:3000
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 5s
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == worker
  api:
    image: registry:5000/api
    build: api
    ports:
      - 81:4000
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 5s
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == worker
    secrets:
      - my_secret
secrets:
  my_secret:
    external: true
