apiVersion: v1
kind: Secret
metadata:
  name: api-secret
type: Opaque
# the data here is base64 and would not normally be added like this!
data:
  a: aGVsbG8=
  b: d29ybGQ=
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    component: api
  ports:
  - port: 3000
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: api
  labels:
    component: api
spec:
  replicas: 2
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      component: api
  template:
    metadata:
      labels:
        component: api
    spec:
      containers:
      - name: api
        image: docker.for.mac.localhost:5000/api@sha256:f0a34bc69902b4589d34ba8b687ed310c85f69c4875a2c44479a3d1c7b559612
        env:
        - name: PORT
          value: "3000"
        ports:
        - name: main-port
          containerPort: 3000
        volumeMounts:
        - name: api-secret-vol
          mountPath: "/run/secrets"
          readOnly: true
        livenessProbe:
          httpGet:
            path: /_health
            port: main-port
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /_health
            port: main-port
          initialDelaySeconds: 3
          periodSeconds: 3
      volumes:
      - name: api-secret-vol
        secret:
          secretName: api-secret
